require pillow>=3.3.0
with pillow < 3.3.0, the call of Image.new()
in brother_ql/brother_ql_create.py line 113
would fail with the following error:

[...]
  File "/usr/lib/python3.4/site-packages/brother_ql/brother_ql_create.py", line 113, in create_label
    new_im = Image.new(im.mode, (device_pixel_width, im.size[1]), (255,)*len(im.mode))
  File "/usr/lib64/python3.4/site-packages/PIL/Image.py", line 2050, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: an integer is required (got type tuple)